AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dev.freaks.BADProject02.SimpleLambdaHandler:: # Use the new handler
      Runtime: java17
      CodeUri: target/BADProject02-0.0.1-SNAPSHOT-aws.jar  # Path to your JAR file
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          AWS_REGION: us-west-2
