AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: dev.freaks.BADProject02.SimpleLambdaHandler::handleRequest  # Correct handler class
      Role: arn:aws:iam::account-id:role/lambda-role  # Update with your role ARN
      FunctionName: MyLambdaFunction
      CodeUri: target/BADProject02-0.0.1-SNAPSHOT-aws.jar  # Path to your JAR
      Runtime: java17
      MemorySize: 512
      Timeout: 15
